name: My Action

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Website
        working-directory: ./website
        run: |
          npm install
          npm install -g gatsby-cli
          gatsby build

      - name: Test
        working-directory: ./website/public
        run: |
          cat index.html | grep -i "Babken"

      - name: test Website
        working-directory: ./website
        run: |
          nnpm install
          npm install -g gatsby-cli
          gatsby serve
          curl "http://localhost:9000" | grep -q "Gatsby"





