name: My Action

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Worl
        run: echo "Hello World!"

      - name: Create new file
        run: |
          bash ./funny-script.sh

