name: My Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Install dependencies
      - name: Install Dependencies
        run: echo "Installing dependencies"
