name: My Action

on:
  push:
    branches:
      - main

env:
  name: ${{ vars.NAME }}
  password: ${{ secrets.PASSWORD }}

jobs:
  Babken:
    runs-on: ubuntu-latest
    steps:
      - name: Test Variables
        run: |
          echo "Name: $name"
          echo "Password: $password"
  Robert:
    runs-on: ubuntu-latest
    needs: Babken
    steps:
      - name: Test Variables
        run: |
          echo "Name: $name"
          echo "Password: $password"

