name: My Action

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run script
        run: |
          echo "Hello, world!"
          ls -la
          touch test.txt
          echo "Hello, world!" > test.txt
          echo "### File contents ###"
          cat test.txt
          docker login -u basoyan -p ${{ secrets.DOCKER_TOKEN }}
          docker build -t my-image -f Dockerfile-app .
          docker tag my-image basoyan/myapp:latest
          docker push basoyan/myapp:latest

