name: My Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Worl
        run: echo "Hello World!"

      # - name: Create new file
      #   run: |
      #     echo "Hello All" >> newfile.txt
      #     echo "Goodbye All" >> newfile.txt
      #     cat newfile.txt

      - name: Test if file exists
        run: |
          if [ -f newfile.txt ]; then
            echo "File exists"
            rm newfile.txt
          else
            echo "File does not exist"
          fi
