name: My Action

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run script
        working-directory: ./website
        run: |
          npm install
          npm install -g gatsby-cli
          gatsby build
          echo "Build complete"
          ls

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            ./website/public


