name: My Action

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker build
        run: |
          docker build -t my-image:latest -f Dockerfile-app .
          mkdir -p images
          docker save my-image:latest > images/my-image.tar
          docker tag my-image:latest basoyan/myapp:${{ github.sha }}
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u basoyan --password-stdin
          docker push basoyan/myapp:${{ github.sha }}

      - uses: actions/upload-artifact@v4
        with:
          name: my-image
          path: images/my-image.tar

