name: My Action

on:
  push:
    branches:
      - main

env:
  name: ${{ vars.NAME }}
  password: ${{ secrets.PASSWORD }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Variables
        run: |
          echo "Name: $name"
          echo "Password: $password"

